# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import  numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
z = np.random.randn(5, 5)
print("Size : {} bytes".format(z.size * z.itemsize))

Size : 200 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
v = np.zeros(10)
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
v = np.arange(1,11)
v = v[::-1]
v

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
v = np.arange(0, 9).reshape((3, 3))
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
v = np.nonzero([1, 2, 0, 0, 4, 0])
v

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.randn(3, 3, 3)

array([[[ 1.84379215, -0.5477291 ,  1.18618086],
        [-1.42225803,  0.41728007, -0.06134513],
        [ 0.1132205 ,  0.31325275, -0.0440327 ]],

       [[ 1.10552413,  1.10597885, -0.26265785],
        [-0.47760091,  0.74590509, -0.81047482],
        [ 0.40455972, -0.47780745, -1.69575551]],

       [[-0.6412735 ,  0.7526056 , -0.3998401 ],
        [ 1.47770826, -0.25709305,  1.65994103],
        [-0.96208628, -0.06677595, -1.47307554]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
m = np.random.randn(10, 10)
print(m)
print(m.max())
print(m.min())

[[ 8.66342968e-01  6.57829764e-01  2.61226104e-01 -9.09254687e-01
  -1.13764800e+00 -1.83703821e+00 -6.78711823e-01  1.16990052e+00
  -1.86908564e-01 -3.80626536e-01]
 [-4.75750438e-01 -2.21032704e-01 -6.15782227e-01 -2.97318216e-01
   1.23347627e+00 -4.88776014e-01 -3.78664477e-01 -4.16625279e-01
  -2.28770725e+00 -1.48560047e-01]
 [-1.23083054e-01 -9.70821248e-01  3.09729226e-01  5.91818099e-01
  -3.40958714e-02 -3.72096051e-01  2.05287687e-03  2.17150517e+00
   1.88569505e+00  1.70348505e+00]
 [ 1.28635215e+00 -1.31149097e+00  5.31379522e-01 -2.22559746e+00
   1.72035839e-01 -2.11522984e-01 -4.06019807e-01  6.74396675e-01
   2.50704791e-01 -1.29327365e+00]
 [-1.00268364e+00  7.14852801e-01 -3.19745580e-01  1.39035881e+00
   8.10438151e-01 -1.23002022e+00 -8.01991251e-02 -9.19498948e-01
   4.28457625e-01  1.85258569e-01]
 [-2.40180590e-01  5.75578829e-01  1.47289447e+00 -1.60014145e+00
   7.76988872e-01  1.13685953e+00 -1.11411123e+00 -1.01646422e+00
   9.89393263e-01  1.19800713e+00

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
v = np.random.randn(30)
print(v)
print(v.mean())

[-0.7050843   0.02638849  1.53855743 -1.75156429  1.10680446  0.7995356
 -0.26011151 -1.53429481  0.88203776 -0.91820378  0.02341618  0.16526484
  0.30349928 -0.60173661 -0.87958537  0.35319209  2.21025795 -0.36813413
 -0.22088258 -0.1982266  -0.45167608  0.16225783  0.93280941  0.53168327
 -0.4822036   0.1690291  -0.59601069  0.65617226 -0.46736451  0.63046355]
0.03520968793974924


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
m = np.ones((5, 5))
m[1:-1, 1:-1] = 0
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
m = np.ones((5, 5))
m = np.pad(m, pad_width=1, mode='constant', constant_values = 0)
m

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
False
False
nan
True
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
m = np.diag(np.arange(1, 5), k=-1)
m

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
m = np.zeros((8,8),dtype=int)
m[1::2, ::2] = 1
m[::2, 1::2] = 1
m

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
np.tile( np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
m = np.random.randn(5, 5)
m - np.mean(m) / np.std(m)

array([[-0.37618769,  0.86693879,  0.90689227, -2.47076071, -0.59820064],
       [ 0.05079462,  1.09167611, -0.47131622,  0.39135912,  0.21233658],
       [-0.11999062, -0.35695165,  0.45730231,  0.81797609, -0.29475271],
       [ 0.60157188, -0.79355218,  0.58478824, -0.18773236, -0.22234069],
       [-0.14629167,  1.56330242,  0.04062476,  0.45993024, -0.62271777]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
np.dot(np.ones((5, 3)), np.ones((3, 2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
v = np.arange(10)
v[(v > 3) & (v < 8)] *= -1
v

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Z**Z

Z <- Z

1j*Z

Z/1/1

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [26]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [27]:
v = np.random.uniform(-10, 10, 10)
print(v)
print(np.where(v > 0, np.ceil(v), np.floor(v)))

[ 2.66164997  1.5569706  -0.70610715  0.43441282  8.52210374 -8.09689547
  2.20621974 -4.37547067  3.96312754  8.54457178]
[ 3.  2. -1.  1.  9. -9.  3. -5.  4.  9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [28]:
a = np.random.randint(0, 10, 10)
b = np.random.randint(0, 10, 10)
print(a)
print(b)
print(np.intersect1d(a, b))

[3 7 8 1 7 7 8 0 6 5]
[6 8 0 2 2 5 0 0 7 1]
[0 1 5 6 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [29]:
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [30]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("yesterday : {}\ntoday : {}\ntomorrow : {}".format(yesterday, today, tomorrow))

yesterday : 2020-09-08
today : 2020-09-09
tomorrow : 2020-09-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [31]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [32]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [33]:
v = np.random.uniform(0, 10, 10)
print(v // 1)
print(v - v % 1)
print(np.floor(v))
print(np.trunc(v))

[4. 5. 2. 5. 3. 9. 2. 5. 2. 0.]
[4. 5. 2. 5. 3. 9. 2. 5. 2. 0.]
[4. 5. 2. 5. 3. 9. 2. 5. 2. 0.]
[4. 5. 2. 5. 3. 9. 2. 5. 2. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [34]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [35]:
def generate():
    for i in range(10):
        yield i

np.fromiter(generate(), dtype=int, count=-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [36]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [37]:
v = np.random.randn(10)
v.sort()
v

array([-1.19458412, -1.17043169, -0.80652968, -0.76594647, -0.66422982,
       -0.25560745, -0.24652371,  0.22978562,  0.24826304,  0.5563428 ])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [38]:
v = np.arange(10)
np.add.reduce(v)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [39]:
A = np.random.randn(10)
B = np.random.randn(10)
print(np.array_equal(A, B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [40]:
m = np.arange(10)
m.flags.writeable = False
m[0] = 100

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [41]:
m = np.random.random((10, 2))
X, Y = m[:, 0], m[:, 1]
R = np.sqrt(X ** 2, Y ** 2)
T = np.arctan2(Y, X)
print(np.concatenate([[R],[T]]))

[[0.38497527 0.69308368 0.20244079 0.21320139 0.84814276 0.52175289
  0.37059668 0.02173552 0.18871805 0.39576709]
 [0.73633751 0.02856392 0.72187722 1.01311288 0.29466379 1.00781333
  0.99630973 1.49480827 0.77787433 0.08731654]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [42]:
v = np.random.random(10)
print(v)
v[v.argmax()] = 0
print(v)

[0.97324933 0.40605988 0.47590639 0.76224456 0.7177584  0.58559651
 0.19070021 0.9477943  0.96239647 0.8410204 ]
[0.         0.40605988 0.47590639 0.76224456 0.7177584  0.58559651
 0.19070021 0.9477943  0.96239647 0.8410204 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [43]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [44]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [45]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
\
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [46]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [47]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

83


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [48]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [49]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.32379731 0.83576585 0.5405289  0.81388599 0.32618354
  0.58775133 0.26631687 0.4458541  0.31804488]
 [0.32379731 0.         0.73938892 0.26638089 0.69775272 0.06786164
  0.52567363 0.25134161 0.1520186  0.62180747]
 [0.83576585 0.73938892 0.         0.54972678 0.05934617 0.67257585
  0.24838614 0.57856876 0.63132372 0.89215444]
 [0.5405289  0.26638089 0.54972678 0.         0.49753359 0.22502029
  0.40189181 0.32965996 0.11505575 0.78367031]
 [0.81388599 0.69775272 0.05934617 0.49753359 0.         0.63181121
  0.23387096 0.55202022 0.58358045 0.8913801 ]
 [0.32618354 0.06786164 0.67257585 0.22502029 0.63181121 0.
  0.45786132 0.19761234 0.12021627 0.60405295]
 [0.58775133 0.52567363 0.24838614 0.40189181 0.23387096 0.45786132
  0.         0.33473604 0.44847    0.66086749]
 [0.26631687 0.25134161 0.57856876 0.32965996 0.55202022 0.19761234
  0.33473604 0.         0.27655708 0.45545927]
 [0.4458541  0.1520186  0.63132372 0.11505575 0.58358045 0.12021627
  0.44847    0.27655

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [50]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[99 99 27 66 16 14 83  4  6 94]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [51]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
Z

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [52]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [53]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [54]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [55]:
X = np.random.rand(5, 5)
X-X.mean(axis=1, keepdims=True)

array([[-0.21270724, -0.10115524, -0.13708467,  0.01981133,  0.43113582],
       [-0.1699922 ,  0.46964926, -0.06675595, -0.08940872, -0.14349239],
       [ 0.32742575, -0.12808459,  0.00586   , -0.2187085 ,  0.01350734],
       [ 0.34020529, -0.39349258,  0.50084034, -0.25608015, -0.1914729 ],
       [ 0.37782558, -0.32269109, -0.07085765,  0.42940829, -0.41368513]])

#### 59. How to sort an array by the nth column? (★★☆)

In [56]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 6 9]
 [0 3 2]
 [5 0 2]]
[[5 0 2]
 [0 3 2]
 [3 6 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [57]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [58]:
Z = np.random.uniform(0,1,10)
val = 0.5
m = Z.flat[np.abs(Z - val).argmin()]
print(m)

0.6197475572741127


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [59]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [60]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [61]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

np.add.at(Z, I, 1)
print(Z)

[3. 2. 6. 2. 3. 3. 2. 2. 3. 4.]
[ 5.  3. 11.  3.  5.  5.  3.  3.  5.  7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [62]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [63]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

4


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [64]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[55 58 68 46]
 [49 61 62 33]
 [57 60 41 48]]
[[55 58 68 46]
 [49 61 62 33]
 [57 60 41 48]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [65]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.43969942 0.41075955 0.5208399  0.45157077 0.55598312 0.57127387
 0.39964263 0.48070532 0.61574409 0.39685808]


#### 69. How to get the diagonal of a dot product? (★★★)

In [66]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
print(np.diag(np.dot(A, B)))

# Fast version
print(np.sum(A * B.T, axis=1))

# Faster version
print(np.einsum("ij,ji->i", A, B))

[1.47263946 1.3288819  2.48719386 1.59792172 2.28208744]
[1.47263946 1.3288819  2.48719386 1.59792172 2.28208744]
[1.47263946 1.3288819  2.48719386 1.59792172 2.28208744]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [67]:
v = np.array([1,2,3,4,5])
n = 3
v0 = np.zeros(len(v) + (len(v) - 1) * n)
v0[::n+1] = v
print(v0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [68]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))
A*B[:, :, None]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★)

In [69]:
A = np.random.randint(0, 10, (5, 5))
print(A)
A[[0, 1]] = A[[1, 0]]
print(A)

[[1 8 5 5 6]
 [8 0 0 6 9]
 [2 5 5 7 2]
 [8 2 3 2 9]
 [8 3 0 0 8]]
[[8 0 0 6 9]
 [1 8 5 5 6]
 [2 5 5 7 2]
 [8 2 3 2 9]
 [8 3 0 0 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [70]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 30) ( 0, 79) ( 4, 25) ( 4, 69) ( 8, 69) ( 8, 90) (15, 41) (15, 79)
 (16, 34) (16, 61) (21, 51) (21, 59) (25, 69) (26, 73) (26, 87) (30, 50)
 (30, 56) (30, 79) (34, 61) (38, 46) (38, 79) (41, 79) (46, 79) (50, 56)
 (51, 59) (56, 74) (56, 86) (69, 90) (73, 87) (74, 86)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [71]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [72]:
def average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] -= ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(20)
print(average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [73]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
    
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [74]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.54677671,  0.83426478,  0.6351336 ,  0.28479128, -0.67627364,
        0.41164159, -0.36735236, -0.66687679, -0.06719297, -0.57139867,
       -0.37809413,  0.83936838,  0.23633175,  0.81271875,  0.35534639,
       -0.52366144, -0.72304476,  0.27240833,  0.69863646,  0.98951702,
        0.88115438,  0.21989675,  0.70726471, -0.45116783,  0.07915249,
       -0.08617935, -0.26910499,  0.7215766 , -0.41148531,  0.3371007 ,
        0.77958524, -0.36828436, -0.53575931,  0.6781043 ,  0.32636035,
       -0.19721876, -0.92679168, -0.58372094, -0.12610817, -0.23106945,
       -0.79801595, -0.39972081, -0.76000636, -0.08222949, -0.17794366,
        0.74230542,  0.20670931,  0.89703462, -0.10511484,  0.34299733,
       -0.55108271, -0.99847855,  0.27352932, -0.73609196, -0.30703818,
        0.83810148, -0.87436653,  0.61227805,  0.61539867, -0.39804162,
        0.77594309, -0.90356191, -0.70501483,  0.56936594, -0.24944309,
        0.61687653,  0.51277721,  0.17359043, -0.50206145,  0.62

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [75]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 5.65819472  1.78181124  4.54029906  7.02190188  7.71435669  6.12641368
 10.44713918 15.02419244  2.16544607  5.02071477]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [76]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.81862327  9.09156927  3.94328384  0.6368386   6.54555306 10.53597188
   3.50414993  9.82662246 13.58748199  1.36743628]
 [ 8.80651064  7.50328755 11.00420124  9.8957735   6.15984275 19.00265643
   6.36304423  0.30276206  1.54290839 14.40084546]
 [ 7.07568276  4.04365545  0.38727807  1.40885518  4.2209748  15.38318429
   6.91642567  8.94385899  9.91445718  2.75497919]
 [ 3.62172122  7.43539704 13.04222914 14.18933339  9.37107418 14.15489325
   0.96433629  3.92581414  3.45014016 15.76445869]
 [ 7.35060701  1.38531159 11.16817046 18.19128849 10.29706769  2.870169
   9.25339708  7.72234605  1.28789409 12.44817728]
 [ 3.78261701  1.6463957   9.99022053 15.42113849  8.30024595  6.24345302
   5.58201301  4.99937992  0.20036683 11.73487989]
 [ 8.17919407  5.56055554  2.42515272  0.8231731   6.42629502 16.14905037
   8.37848226 11.17966106 11.92744665  0.8567579 ]
 [ 9.10901852  0.56770653  9.83767118 17.98608141  9.46812556  0.89092236
  10.68985821  7.47291231  0.09068615 10.88405325]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [77]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 6 8 9 1 7 3 0 1 0]
 [4 6 6 3 7 7 9 2 6 4]
 [2 1 1 5 6 4 1 7 0 4]
 [8 0 2 3 2 3 1 8 7 4]
 [0 1 4 4 4 4 4 2 9 2]
 [9 1 8 7 0 3 8 1 9 4]
 [5 2 0 5 1 9 1 3 0 7]
 [3 1 1 3 6 9 1 3 3 8]
 [4 4 1 6 4 3 0 5 4 3]
 [7 8 6 2 6 7 9 6 5 8]]
[[0 0 0 0 0]
 [0 9 6 8 9]
 [0 4 6 6 3]
 [0 2 1 1 5]
 [0 8 0 2 3]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [78]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [79]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [80]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [81]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 0 0]
   [0 2 4]
   [4 1 1]]

  [[0 0 0]
   [2 4 1]
   [1 1 4]]

  [[0 0 0]
   [4 1 4]
   [1 4 2]]

  [[0 0 2]
   [1 4 1]
   [4 2 4]]

  [[0 2 2]
   [4 1 1]
   [2 4 0]]

  [[2 2 3]
   [1 1 0]
   [4 0 3]]

  [[2 3 0]
   [1 0 2]
   [0 3 1]]

  [[3 0 1]
   [0 2 1]
   [3 1 3]]]


 [[[0 2 4]
   [4 1 1]
   [2 2 3]]

  [[2 4 1]
   [1 1 4]
   [2 3 3]]

  [[4 1 4]
   [1 4 2]
   [3 3 2]]

  [[1 4 1]
   [4 2 4]
   [3 2 0]]

  [[4 1 1]
   [2 4 0]
   [2 0 3]]

  [[1 1 0]
   [4 0 3]
   [0 3 3]]

  [[1 0 2]
   [0 3 1]
   [3 3 1]]

  [[0 2 1]
   [3 1 3]
   [3 1 4]]]


 [[[4 1 1]
   [2 2 3]
   [0 3 0]]

  [[1 1 4]
   [2 3 3]
   [3 0 4]]

  [[1 4 2]
   [3 3 2]
   [0 4 4]]

  [[4 2 4]
   [3 2 0]
   [4 4 0]]

  [[2 4 0]
   [2 0 3]
   [4 0 2]]

  [[4 0 3]
   [0 3 3]
   [0 2 1]]

  [[0 3 1]
   [3 3 1]
   [2 1 2]]

  [[3 1 3]
   [3 1 4]
   [1 2 2]]]


 [[[2 2 3]
   [0 3 0]
   [1 4 3]]

  [[2 3 3]
   [3 0 4]
   [4 3 4]]

  [[3 3 2]
   [0 4 4]
   [3 4 1]]

  [[3 2 0]
   [4 4 0]
   [4 1 0]]

  [[2 0 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [82]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5  6  9  6  8]
 [ 6  7 11  8  7]
 [ 9 11  9 42  8]
 [ 6  8 42  5 11]
 [ 8  7  8 11  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [83]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [84]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [85]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): 
    Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [86]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9998 9995 9997 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [87]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [88]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [89]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.49 s ± 254 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
445 ms ± 33 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
245 ms ± 17.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [90]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [91]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 0 4]
 [0 3 2]
 [1 1 3]
 [4 3 1]
 [2 4 0]
 [2 2 1]
 [1 3 0]
 [4 0 2]
 [3 2 4]
 [1 1 2]]
[[2 0 4]
 [0 3 2]
 [1 1 3]
 [4 3 1]
 [2 4 0]
 [2 2 1]
 [1 3 0]
 [4 0 2]
 [3 2 4]
 [1 1 2]]
[[2 0 4]
 [0 3 2]
 [1 1 3]
 [4 3 1]
 [2 4 0]
 [2 2 1]
 [1 3 0]
 [4 0 2]
 [3 2 4]
 [1 1 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [92]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [93]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 1]]
[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [94]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[1.23246972e-01, 1.70082188e-01, 2.89790138e-01, 9.43829404e-03,
        2.65483613e-01, 1.26700819e-01, 8.79779432e-02, 9.30676681e-02,
        1.71534606e-01, 4.54749319e-01],
       [2.08689160e-01, 2.87993354e-01, 4.90690031e-01, 1.59814852e-02,
        4.49532766e-01, 2.14537422e-01, 1.48969527e-01, 1.57587754e-01,
        2.90452675e-01, 7.70008804e-01],
       [1.02584104e-01, 1.41567201e-01, 2.41205615e-01, 7.85592474e-03,
        2.20974180e-01, 1.05458899e-01, 7.32280747e-02, 7.74644860e-02,
        1.42776115e-01, 3.78508702e-01],
       [4.70731016e-03, 6.49614021e-03, 1.10682806e-02, 3.60487376e-04,
        1.01399141e-02, 4.83922685e-03, 3.36024050e-03, 3.55463808e-03,
        6.55161405e-03, 1.73687520e-02],
       [8.02096019e-02, 1.10690140e-01, 1.88596533e-01, 6.14247796e-03,
        1.72777754e-01, 8.24573792e-02, 5.72563828e-02, 6.05687953e-02,
        1.11635379e-01, 2.95952601e-01],
       [2.06918899e-01, 2.85550375e-01, 4.86527624e-01, 1.58459180e-02,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [95]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [96]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [97]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.23920367  0.14786874]
